services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quickvpn_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Moscow