"""Add access_key to Subscription model

Revision ID: 0e897577e28c
Revises: 77b1c100315b
Create Date: 2025-07-30 19:53:49.341322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e897577e28c'
down_revision: Union[str, Sequence[str], None] = '77b1c100315b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('access_key', sa.String(), nullable=False))
    op.create_index(op.f('ix_subscriptions_access_key'), 'subscriptions', ['access_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_access_key'), table_name='subscriptions')
    op.drop_column('subscriptions', 'access_key')
    # ### end Alembic commands ###
