"""Add had_first_purchase flag to User model

Revision ID: 77b1c100315b
Revises: dc24cc2b4f17
Create Date: 2025-07-30 16:22:56.279569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b1c100315b'
down_revision: Union[str, Sequence[str], None] = 'dc24cc2b4f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('had_first_purchase', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'had_first_purchase')
    # ### end Alembic commands ###
