"""Добавляем новые поля в Subscription

Revision ID: cbcc844e91ac
Revises: 603dc82a1bf3
Create Date: 2025-11-12 04:07:33.376095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcc844e91ac'
down_revision: Union[str, Sequence[str], None] = '603dc82a1bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('hwidDeviceLimit', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('first_connected', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'first_connected')
    op.drop_column('subscriptions', 'hwidDeviceLimit')
    op.drop_column('subscriptions', 'description')
    # ### end Alembic commands ###
