"""added user.is_active

Revision ID: e9aa8bb92e9d
Revises: cbcc844e91ac
Create Date: 2025-11-22 17:04:18.528024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9aa8bb92e9d'
down_revision: Union[str, Sequence[str], None] = 'cbcc844e91ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.execute("UPDATE users SET is_active = 1")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
