"""init

Revision ID: 5e8b6eb98711
Revises: 
Create Date: 2025-08-31 23:22:58.851337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8b6eb98711'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promocodes')),
    sa.UniqueConstraint('code', name=op.f('uq_promocodes_code'))
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariffs'))
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('has_trial', sa.Boolean(), nullable=False),
    sa.Column('had_first_purchase', sa.Boolean(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.telegram_id'], name=op.f('fk_users_inviter_id_users')),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'LIMITED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('remnawave_uuid', sa.String(length=36), nullable=False),
    sa.Column('remnawave_short_uuid', sa.String(length=48), nullable=False),
    sa.Column('subscription_name', sa.String(), nullable=False),
    sa.Column('subscription_url', sa.String(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=True),
    sa.Column('promo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['promo_id'], ['promocodes.id'], name=op.f('fk_subscriptions_promo_id_promocodes')),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name=op.f('fk_subscriptions_tariff_id_tariffs')),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], name=op.f('fk_subscriptions_telegram_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_remnawave_short_uuid'), 'subscriptions', ['remnawave_short_uuid'], unique=True)
    op.create_index(op.f('ix_subscriptions_remnawave_uuid'), 'subscriptions', ['remnawave_uuid'], unique=True)
    op.create_table('payments_gateways',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('method', sa.Enum('yookassa', 'crypto', 'tg_stars', name='paymentmethod'), nullable=False),
    sa.Column('external_payment_id', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payments_gateways_subscription_id_subscriptions')),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name=op.f('fk_payments_gateways_tariff_id_tariffs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('fk_payments_gateways_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments_gateways')),
    sa.UniqueConstraint('external_payment_id', name=op.f('uq_payments_gateways_external_payment_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments_gateways')
    op.drop_index(op.f('ix_subscriptions_remnawave_uuid'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_remnawave_short_uuid'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_table('users')
    op.drop_table('tariffs')
    op.drop_table('promocodes')
    # ### end Alembic commands ###
